[package]
name = "from-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
syn = "2.0.38"
quote = "1.0.33"